/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package t3lpfinal;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio
 */
public class batalla extends javax.swing.JFrame {
    public ArrayList <Entrenador> listap;
    /**
     * Creates new form batalla
     */
    
    /**
     * Creates new form batalla
     * @param lista
     */
    public batalla(ArrayList <Entrenador> lista) {
        listap=lista;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
        if(listap.get(0).vidaPlagiamonfinal()==0){
            //Lanzar una wea de perdiste
            JOptionPane.showMessageDialog(null,"perdiste, eres muy penca");
            System.exit(0);
        }
        if(evt.VK_1==evt.getKeyCode()){
            Random  rnd = new Random();
            int random=(rnd.nextInt()%2)+1;
            //ataque principal
            String plagluchador=listap.get(0).getPlagiamon().getNombre();
            if(listap.get(1).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(1).getPlagiamon(),1,random);
            }
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(2).getPlagiamon(),1,random);
            }            
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()==0 && listap.get(3).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(3).getPlagiamon(),1,random);
            }
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()==0 && listap.get(3).vidaPlagiamonfinal()==0){
                //ganaste aquí;
                JOptionPane.showMessageDialog(null,"felicidades ganaste");
                System.exit(0);
            }
        }
        if(evt.VK_2==evt.getKeyCode()){
            Random  rnd = new Random();
            int random=(rnd.nextInt()%2)+1;
            //ataque principal
            String plagluchador=listap.get(0).getPlagiamon().getNombre();
            if(listap.get(1).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(1).getPlagiamon(),2,random);
            }
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(2).getPlagiamon(),2,random);
            }            
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()==0 && listap.get(3).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(3).getPlagiamon(),2,random);
            }
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()==0 && listap.get(3).vidaPlagiamonfinal()==0){
                //ganaste aquí;
                JOptionPane.showMessageDialog(null,"felicidades ganaste");
                System.exit(0);
            }
        }
        if(evt.VK_ESCAPE==evt.getKeyCode()){
        
            //ataque principal
            System.exit(0);
        }
    }//GEN-LAST:event_formKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if(listap.get(0).vidaPlagiamonfinal()==0){
            //Lanzar una wea de perdiste
            System.exit(0);
        }
        if(evt.VK_1==evt.getKeyCode()){
            Random  rnd = new Random();
            int random=(rnd.nextInt()%2)+1;
            //ataque principal
            String plagluchador=listap.get(0).getPlagiamon().getNombre();
            if(listap.get(1).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(1).getPlagiamon(),1,random);
            }
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(2).getPlagiamon(),1,random);
            }            
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()==0 && listap.get(3).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(3).getPlagiamon(),1,random);
            }
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()==0 && listap.get(3).vidaPlagiamonfinal()==0){
                //ganaste aquí;
                System.exit(0);
            }
        }
        if(evt.VK_2==evt.getKeyCode()){
            Random  rnd = new Random();
            int random=(rnd.nextInt()%2)+1;
            //ataque principal
            String plagluchador=listap.get(0).getPlagiamon().getNombre();
            if(listap.get(1).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(1).getPlagiamon(),2,random);
            }
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(2).getPlagiamon(),2,random);
            }            
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()==0 && listap.get(3).vidaPlagiamonfinal()>0){
                listap.get(0).batalla(listap.get(0).getPlagiamon(),listap.get(3).getPlagiamon(),2,random);
            }
            if(listap.get(1).vidaPlagiamonfinal()==0 && listap.get(2).vidaPlagiamonfinal()==0 && listap.get(3).vidaPlagiamonfinal()==0){
                //ganaste aquí;
                System.exit(0);
            }
        }
        if(evt.VK_ESCAPE==evt.getKeyCode()){
        
            //ataque principal
            System.exit(0);
        }
        
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
